export const products = [
    {
        id: 1,
        name: "Caja impresa",
        brand: "carton",
        package: "Unidad",
        img: "https://tienda.papeleradelmar.com.ar/4354-home_default/caja-e-commerce-impresa-con-manija-25x16x10cm.jpg",
        price: 250,
        description: "Ideal para regalo",
        category: 1,
    },
    {
        id: 2,
        name: "Caja con visor",
        brand: "Carton",
        package: "Unidad",
        img: "https://tienda.papeleradelmar.com.ar/4337-home_default/caja-con-visor-kraft-impresa-.jpg",
        price: 200,
        description: "Ideal para regalo",
        category: 1,
    },
    {
        id: 3,
        name: "Caja archivo",
        brand: "Carton",
        package: "Unidad",
        img: "https://tienda.papeleradelmar.com.ar/3279-home_default/caja-para-archivo-carton-marron.jpg",
        price: 100,
        description: "Es ideal para guardar documentacion",
        category: 1,
    },
    {
        id: 4,
        name: "Bolsa de tela",
        brand: "Fantasia",
        package: "Unidad",
        img: "https://tienda.papeleradelmar.com.ar/3189-home_default/bolsas-de-tela-15x265-cm-fantasia-rinon.jpg",
        price: 150,
        description: "Bolsas de tela, muy buena calidad, diferentes motivos",
        category: 2,
    },
    {
        id: 5,
        name: "Bolsas de tela",
        brand: "Laminada",
        package: "Unidad",
        img: "https://tienda.papeleradelmar.com.ar/3212-home_default/bolsas-de-tela-30x30-cm-asa-laminada.jpg",
        price: 300,
        description: "Bolsas de tela, muy buena calidad, diferentes motivos",
        category: 2,
    },
    {
        id: 6,
        name: "Guantes Nitrilo",
        brand: "Negro",
        package: "x100 unidades ",
        img: "https://tienda.papeleradelmar.com.ar/3534-home_default/guantes-de-nitrilo-chico.jpg",
        price: 900,
        description: "Guantes nitrilo excelente calidad",
        category: 3,
    },
    {
        id: 7,
        name: "Guantes Latex",
        brand: "Blanco",
        package: "x100 unidades",
        img: "https://tienda.papeleradelmar.com.ar/2494-home_default/guantes-de-latex-chico.jpg",
        price: 900,
        description: "Guantes latex excelente calidad",
        category: 3,
    },
    {
        id: 8,
        name: "Rollo Cocina",
        brand: "Premium",
        package: "x2",
        img: "https://tienda.papeleradelmar.com.ar/3774-home_default/bulto-rollos-de-cocina-x-20-rollos-x-100-panos-campanita.jpg",
        price: 600,
        description: "Calidad premium",
        category: 4,
    },
    {
        id: 9,
        name: "Rollo cocina",
        brand: "Eco",
        package: "x3",
        img: "https://tienda.papeleradelmar.com.ar/3773-home_default/bulto-rollos-de-cocina-x-24-rollos-x-60-panos-campanita-.jpg",
        price: 500,
        description: "Calidad eco",
        category: 4,
    },
];
