export const products = [
    {
        id: 1,
        name: "Caja impresa",
        brand: "carton",
        package: "Unidad",
        img: "https://tienda.papeleradelmar.com.ar/4354-home_default/caja-e-commerce-impresa-con-manija-25x16x10cm.jpg",
        price: 250,
        description: "Ideal para regalo",
        category: 1,
    },
    {
        id: 2,
        name: "Caja con visor",
        brand: "Carton",
        package: "Unidad",
        img: "https://tienda.papeleradelmar.com.ar/4337-home_default/caja-con-visor-kraft-impresa-.jpg",
        price: 200,
        description: "Ideal para regalo",
        category: 1,
    },
    {
        id: 3,
        name: "Caja archivo",
        brand: "Carton",
        package: "Unidad",
        img: "https://tienda.papeleradelmar.com.ar/3279-home_default/caja-para-archivo-carton-marron.jpg",
        price: 100,
        description: "Es ideal para guardar documentacion",
        category: 1,
    },
    {
        id: 4,
        name: "Bolsa de tela",
        brand: "Fantasia",
        package: "Unidad",
        img: "https://tienda.papeleradelmar.com.ar/3189-home_default/bolsas-de-tela-15x265-cm-fantasia-rinon.jpg",
        price: 150,
        description: "Bolsas de tela, muy buena calidad, diferentes motivos",
        category: 2,
    },
    {
        id: 5,
        name: "Bolsas de tela",
        brand: "Laminada",
        package: "Unidad",
        img: "https://tienda.papeleradelmar.com.ar/3212-home_default/bolsas-de-tela-30x30-cm-asa-laminada.jpg",
        price: 300,
        description: "Bolsas de tela, muy buena calidad, diferentes motivos",
        category: 2,
    },
    {
        id: 6,
        name: "Guantes Nitrilo",
        brand: "Negro",
        package: "x100 unidades ",
        img: "https://tienda.papeleradelmar.com.ar/3534-home_default/guantes-de-nitrilo-chico.jpg",
        price: 900,
        description: "Guantes nitrilo excelente calidad",
        category: 3,
    },
    {
        id: 7,
        name: "Guantes Latex",
        brand: "Blanco",
        package: "x100 unidades",
        img: "https://tienda.papeleradelmar.com.ar/2494-home_default/guantes-de-latex-chico.jpg",
        price: 900,
        description: "Guantes latex excelente calidad",
        category: 3,
    },
    {
        id: 8,
        name: "Rollo Cocina",
        brand: "Premium",
        package: "x2",
        img: "https://tienda.papeleradelmar.com.ar/3774-home_default/bulto-rollos-de-cocina-x-20-rollos-x-100-panos-campanita.jpg",
        price: 600,
        description: "Calidad premium",
        category: 4,
    },
    {
        id: 9,
        name: "Rollo cocina",
        brand: "Eco",
        package: "x3",
        img: "https://tienda.papeleradelmar.com.ar/3773-home_default/bulto-rollos-de-cocina-x-24-rollos-x-60-panos-campanita-.jpg",
        price: 500,
        description: "Calidad eco",
        category: 4,
    },
    {
        id: 10,
        name: "Rollo Higienico Max",
        brand: "Premium",
        package: "80 mts",
        img: "https://tienda.papeleradelmar.com.ar/3795-home_default/bulto-papel-higienico-x-80-mts-10-paq-x-4u-higienol.jpg",
        price: 500,
        description: "Calidad Premium",
        category: 4,
    },
    {
        id: 11,
        name: "Rollo De Cocina Campanita",
        brand: "Eco",
        package: "x3",
        img: "https://tienda.papeleradelmar.com.ar/4362-home_default/bulto-rollos-de-cocina-x-30-rollos-x-50-panos-campanita.jpg",
        price: 500,
        description: "Calidad eco",
        category: 4,
    },
    {
        id: 12,
        name: "Bolsas de tela",
        brand: "Lisa",
        package: "Unidad",
        img: "https://tienda.papeleradelmar.com.ar/3186-home_default/bolsas-de-tela-15x265-cm-lisa-rinon.jpg",
        price: 300,
        description: "Bolsas de tela, muy buena calidad, diferentes colores",
        category: 2,
    },
    {
        id: 13,
        name: "Bolsas de Madera",
        brand: "Lisa",
        package: "Unidad",
        img: "https://tienda.papeleradelmar.com.ar/3145-home_default/bolsas-de-papel-madera-con-manija-14x8x20-cm.jpg",
        price: 300,
        description: "Bolsas de Madera, muy buena calidad, diferentes tamaños",
        category: 2,
    },
    {
        id: 14,
        name: "Guantes De Polietileno",
        brand: "Transparente",
        package: "x100 unidades",
        img: "https://tienda.papeleradelmar.com.ar/2495-home_default/guantes-polietileno.jpg",
        price: 900,
        description: "Guantes polietileno excelente calidad",
        category: 3,
    },
    {
        id: 15,
        name: "Caja De Torta",
        brand: "Carton",
        package: "Unidad",
        img: "https://tienda.papeleradelmar.com.ar/3235-home_default/caja-para-torta-con-manija-grande-impresa.jpg",
        price: 100,
        description: "Es ideal para regalo",
        category: 1,
    },
    {
        id: 16,
        name: "Caja Con Visor",
        brand: "Carton",
        package: "Unidad",
        img: "https://tienda.papeleradelmar.com.ar/3261-home_default/cajas-con-visor-325x24x10-cm-impresa.jpg",
        price: 100,
        description: "Es ideal para desayunos",
        category: 1,
    },
];
